#!/bin/bash
PSB=/var/cache/psb

if [ ! -d ${PSB} ]; then
	mkdir -p $PSB
fi

src=(
	ninja 
	meson 
	protobuf3
	protobuf-c
	libsmbios
	gcab
	libxmlb
	lxml
	fwupd 
	gnome-keyring 
	sleuthkit 
	lsb-release 
	raptor
	gnome-menus 
	python-distutils-extra 
	isodate 
	gnome-common 
	bamf 
	plank 
	granite 
	granite7
        gnome-desktop
        libsoup3
        geocode-glib
        gsettings-desktop-schemas
        libgweather4
        geoclue2
        gcr4
        gnome-settings-daemon
        mutter
	gala 
	libhandy
        pantheon-notifications
        telepathy-glib
	wingpanel 
	switchboard 
	rdflib 
	zeitgeist 
	pantheon-applications-menu
        cerbere
        python-onboard
        liblouis
        orca
	pantheon-agent-polkit 
	wingpanel-indicator-session 
	pantheon-session 
	xfce4-dev-tools 
	libxfce4util 
	xfconf 
	libxfce4ui 
	exo
        tumbler	
	elementary-wallpapers 
	elementary-dock 
	switchboard-plug-pantheon-shell
	libstemmer 
	AppStream 
	wingpanel-indicator-keyboard
	libgnomekbd 
	switchboard-plug-keyboard 
	wingpanel-indicator-sound 
	switchboard-plug-sound
	webkit2gtk4.1
	evolution-data-server 
	wingpanel-indicator-datetime 
	switchboard-plug-datetime 
	libcloudproviders
        http-parser
        libgit2
        libgit2-glib
	pantheon-filemanager 
	gtk-theme-elementary 
	pantheon-icons 
	pantheon-terminal 
	pantheon-tweaks 
	switchboard-plug-network
        rest
        webkit2gtk
	elementary-photos 
	bash-completion 
	wingpanel-indicator-power 
	switchboard-plug-power 
	switchboard-plug-notifications 
	wingpanel-indicator-notifications 
	switchboard-plug-display 
	gtkspell3
	gtksourceview4
	libpeas 
	elementary-code
	folks 
	elementary-mail 
	switchboard-plug-onlineaccounts 
	pantheon-default-settings 
	pantheon-screenshot
	bubblewrap
	libostree
	flatpak
	pantheon-sideload
	cogl
	clutter
	clutter-gst 
	pantheon-videos 
	switchboard-plug-applications 
	ayatana-ido 
	libayatana-indicator 
	libgdiplus 
	mono 
	gtk-sharp 
	perl-xml-libxml 
	libayatana-appindicator 
	ayatana-indicator-application 
	wingpanel-indicator-ayatana 
	switcheroo-control 
	switchboard-plug-about 
	switchboard-plug-locale 
	switchboard-plug-useraccounts 
	switchboard-plug-security-privacy 
	switchboard-plug-a11y 
	switchboard-plug-mouse-touchpad 
	pantheon-settings-daemon 
	libgda 
	elementary-music 
	switchboard-plug-printers
	libadwaita 
	pantheon-onboarding
	libchamplain
	gnome-online-accounts
	libgdata 
	elementary-tasks 
	switchboard-plug-wacom 
	switchboard-plug-sharing 
	switchboard-plug-bluetooth 
	elementary-camera 
	elementary-calendar 
	wingpanel-indicator-nightlight 
	elementary-contractor 
	elementary-print 
	elementary-fonts 
	wingpanel-indicator-network 
	indicator-application 
	lightdm 
	lightdm-gtk-greeter 
	lightdm-pantheon-greeter
)

for i in ${src[@]}; do
	cd ${i} || exit 1
	sh ${i}.SlackBuild || exit 1
	cd ..
done

exit 0


